name: Deploy Next.js Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js App
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/fe_key
          chmod 600 ~/.ssh/fe_key
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/fe_key ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} << 'EOSSH'
            set -e

            APP_DIR=/home/ubuntu/test-app-fe
            REPO=https://github.com/SGShekhar/test-app-fe.git

            echo "Checking if app directory exists..."
            if [ ! -d "$APP_DIR" ]; then
              echo "Directory does not exist. Cloning repo..."
              git clone $REPO $APP_DIR
            fi

            cd $APP_DIR

            echo "Fetching latest changes..."
            git fetch --all
            git reset --hard origin/main

            echo "Installing dependencies..."
            npm ci

            echo "Building app..."
            npm run build

            echo "Restarting PM2 process..."
            pm2 restart next-app || pm2 start npm --name "next-app" -- start

            echo "Deployment completed successfully."
          EOSSH
