name: Deploy Next.js Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-24.04
    environment: deploy-env-fe

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/fe_key
          chmod 600 ~/.ssh/fe_key
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/fe_key ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} << EOF
            set -e

            echo "Navigating to project directory..."
            cd /home/ubuntu/test-app-fe  # Update to your app path

            echo "Pulling latest changes..."
            git fetch --all
            git reset --hard origin/main

            echo "Creating .env.local file..."
          
          NEXT_PUBLIC_SECOND_MY_SECRET_ENV=${{ vars.NEXT_PUBLIC_SECOND_MY_SECRET_ENV }}
          EOL

            echo "Installing dependencies..."
            npm ci

            echo "Building app..."
            npm run build

            echo "Restarting PM2..."
            pm2 restart next-app || pm2 start npm --name "next-app" -- start

            echo "Deployment completed successfully."
          EOF
